# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgateway.proto\x12\x0fmmws.gateway.v1\"\x97\x01\n\x13ReadRegisterRequest\x12\x0f\n\x07profile\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12\x0e\n\x06serial\x18\x04 \x01(\t\x12\x10\n\x08password\x18\x05 \x01(\t\x12\x0c\n\x04obis\x18\x06 \x01(\t\x12\x12\n\ntimeout_ms\x18\x07 \x01(\x05\x12\x0f\n\x07retries\x18\x08 \x01(\x05\"z\n\x14ReadRegisterResponse\x12+\n\x05value\x18\x01 \x01(\x0b\x32\x1a.mmws.gateway.v1.ReadValueH\x00\x12+\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1a.mmws.gateway.v1.ReadErrorH\x00\x42\x08\n\x06result\"\x1f\n\tReadValue\x12\x12\n\nvalue_json\x18\x01 \x01(\t\"U\n\tReadError\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nis_partial\x18\x03 \x01(\x08\x12\x15\n\rraw_frame_hex\x18\x04 \x01(\t\"\x14\n\x12HealthCheckRequest\"9\n\x13HealthCheckResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x16\n\x0e\x64river_version\x18\x02 \x01(\t2\xc7\x01\n\x0eGatewayService\x12[\n\x0cReadRegister\x12$.mmws.gateway.v1.ReadRegisterRequest\x1a%.mmws.gateway.v1.ReadRegisterResponse\x12X\n\x0bHealthCheck\x12#.mmws.gateway.v1.HealthCheckRequest\x1a$.mmws.gateway.v1.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_READREGISTERREQUEST']._serialized_start=35
  _globals['_READREGISTERREQUEST']._serialized_end=186
  _globals['_READREGISTERRESPONSE']._serialized_start=188
  _globals['_READREGISTERRESPONSE']._serialized_end=310
  _globals['_READVALUE']._serialized_start=312
  _globals['_READVALUE']._serialized_end=343
  _globals['_READERROR']._serialized_start=345
  _globals['_READERROR']._serialized_end=430
  _globals['_HEALTHCHECKREQUEST']._serialized_start=432
  _globals['_HEALTHCHECKREQUEST']._serialized_end=452
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=454
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=511
  _globals['_GATEWAYSERVICE']._serialized_start=514
  _globals['_GATEWAYSERVICE']._serialized_end=713
# @@protoc_insertion_point(module_scope)
