# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import gateway_pb2 as gateway__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewayServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadRegister = channel.unary_unary(
                '/mmws.gateway.v1.GatewayService/ReadRegister',
                request_serializer=gateway__pb2.ReadRegisterRequest.SerializeToString,
                response_deserializer=gateway__pb2.ReadRegisterResponse.FromString,
                _registered_method=True)
        self.WriteRegister = channel.unary_unary(
                '/mmws.gateway.v1.GatewayService/WriteRegister',
                request_serializer=gateway__pb2.WriteRegisterRequest.SerializeToString,
                response_deserializer=gateway__pb2.WriteRegisterResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/mmws.gateway.v1.GatewayService/HealthCheck',
                request_serializer=gateway__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=gateway__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.ReadLoadProfile = channel.unary_stream(
                '/mmws.gateway.v1.GatewayService/ReadLoadProfile',
                request_serializer=gateway__pb2.ReadLoadProfileRequest.SerializeToString,
                response_deserializer=gateway__pb2.ReadLoadProfileResponse.FromString,
                _registered_method=True)
        self.DisconnectMeter = channel.unary_unary(
                '/mmws.gateway.v1.GatewayService/DisconnectMeter',
                request_serializer=gateway__pb2.DisconnectMeterRequest.SerializeToString,
                response_deserializer=gateway__pb2.DisconnectMeterResponse.FromString,
                _registered_method=True)
        self.ListCallHomeSerials = channel.unary_unary(
                '/mmws.gateway.v1.GatewayService/ListCallHomeSerials',
                request_serializer=gateway__pb2.ListCallHomeSerialsRequest.SerializeToString,
                response_deserializer=gateway__pb2.ListCallHomeSerialsResponse.FromString,
                _registered_method=True)
        self.SetCallHomePort = channel.unary_unary(
                '/mmws.gateway.v1.GatewayService/SetCallHomePort',
                request_serializer=gateway__pb2.SetCallHomePortRequest.SerializeToString,
                response_deserializer=gateway__pb2.SetCallHomePortResponse.FromString,
                _registered_method=True)


class GatewayServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ReadRegister(self, request, context):
        """Читает одно значение (COSEM Register) со счётчика по одному из трёх
        протокольных профилей Этапа 0. Синхронный RPC — асинхронность (job_id,
        очередь) реализуется на стороне Backend, Gateway остаётся stateless
        относительно пользователей/задач (Promt_MMWS.md, раздел 3, принцип 1).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteRegister(self, request, context):
        """Записывает один атрибут COSEM-объекта (Этап 2, ТЗ п. 4.2.4). Как и
        ReadRegister — синхронный RPC, асинхронность и аудит записи
        (parameter_write_history) реализуются на стороне Backend.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Проверка доступности конкретного экземпляра Gateway (используется
        Backend'ом для heartbeat в реестре gateways, ТЗ п. 4.1.1).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadLoadProfile(self, request, context):
        """Профиль нагрузки (Этап 3, ТЗ п. 4.2.3) — server-streaming: каждая
        строка буфера отдаётся отдельным сообщением сразу, как только она
        полностью собрана из принятых датаблоков (см.
        protocols.hdlc_dlms.read_load_profile), а не одним ответом по
        завершении всей передачи. Именно ради этого сценария изначально
        выбран gRPC (Promt_MMWS.md — потоковая передача данных профиля
        нагрузки), а не обычный REST/HTTP между Backend и Gateway. Если
        соединение со счётчиком обрывается посреди передачи, Backend
        получает через RpcError все строки, отправленные ДО обрыва (не
        теряет их) и решает, докачивать ли остаток (is_partial) — сам
        Gateway не хранит состояние между вызовами (Promt_MMWS.md, раздел
        3, принцип 1).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisconnectMeter(self, request, context):
        """Удалённое отключение/подключение счётчика (Этап 5, ТЗ п.4.2.10) —
        ACTION-сервис DLMS на объект Disconnect Control (класс 70, рабочая
        гипотеза адреса — см. DECISIONS.md). Синхронный RPC, как
        ReadRegister/WriteRegister — асинхронность (job_id, batch_id при
        пакетной операции от биллинга) реализуется на стороне Backend.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCallHomeSerials(self, request, context):
        """Этап 6 (обнаружение новых счётчиков) — все серийные номера,
        опознанные call-home пулом этого Gateway с момента запуска процесса
        (см. callhome.CallHomePool.list_seen_serials), независимо от того,
        уже ли Backend знает о них. Backend периодически опрашивает этот
        метод и заводит в справочник ранее неизвестные серийники со
        статусом "installed" — оператор видит их и решает, принимать ли в
        работу, вместо того чтобы заранее знать серийный номер откуда-то ещё.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCallHomePort(self, request, context):
        """Этап 6 — живая смена порта, который слушает call-home пул Gateway,
        БЕЗ перезапуска процесса/контейнера (CallHomePool.stop()+start() на
        новом порту). Используется панелью суперадминистратора.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadRegister': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadRegister,
                    request_deserializer=gateway__pb2.ReadRegisterRequest.FromString,
                    response_serializer=gateway__pb2.ReadRegisterResponse.SerializeToString,
            ),
            'WriteRegister': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteRegister,
                    request_deserializer=gateway__pb2.WriteRegisterRequest.FromString,
                    response_serializer=gateway__pb2.WriteRegisterResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=gateway__pb2.HealthCheckRequest.FromString,
                    response_serializer=gateway__pb2.HealthCheckResponse.SerializeToString,
            ),
            'ReadLoadProfile': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadLoadProfile,
                    request_deserializer=gateway__pb2.ReadLoadProfileRequest.FromString,
                    response_serializer=gateway__pb2.ReadLoadProfileResponse.SerializeToString,
            ),
            'DisconnectMeter': grpc.unary_unary_rpc_method_handler(
                    servicer.DisconnectMeter,
                    request_deserializer=gateway__pb2.DisconnectMeterRequest.FromString,
                    response_serializer=gateway__pb2.DisconnectMeterResponse.SerializeToString,
            ),
            'ListCallHomeSerials': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCallHomeSerials,
                    request_deserializer=gateway__pb2.ListCallHomeSerialsRequest.FromString,
                    response_serializer=gateway__pb2.ListCallHomeSerialsResponse.SerializeToString,
            ),
            'SetCallHomePort': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCallHomePort,
                    request_deserializer=gateway__pb2.SetCallHomePortRequest.FromString,
                    response_serializer=gateway__pb2.SetCallHomePortResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mmws.gateway.v1.GatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mmws.gateway.v1.GatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadRegister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmws.gateway.v1.GatewayService/ReadRegister',
            gateway__pb2.ReadRegisterRequest.SerializeToString,
            gateway__pb2.ReadRegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteRegister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmws.gateway.v1.GatewayService/WriteRegister',
            gateway__pb2.WriteRegisterRequest.SerializeToString,
            gateway__pb2.WriteRegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmws.gateway.v1.GatewayService/HealthCheck',
            gateway__pb2.HealthCheckRequest.SerializeToString,
            gateway__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadLoadProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mmws.gateway.v1.GatewayService/ReadLoadProfile',
            gateway__pb2.ReadLoadProfileRequest.SerializeToString,
            gateway__pb2.ReadLoadProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisconnectMeter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmws.gateway.v1.GatewayService/DisconnectMeter',
            gateway__pb2.DisconnectMeterRequest.SerializeToString,
            gateway__pb2.DisconnectMeterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCallHomeSerials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmws.gateway.v1.GatewayService/ListCallHomeSerials',
            gateway__pb2.ListCallHomeSerialsRequest.SerializeToString,
            gateway__pb2.ListCallHomeSerialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCallHomePort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mmws.gateway.v1.GatewayService/SetCallHomePort',
            gateway__pb2.SetCallHomePortRequest.SerializeToString,
            gateway__pb2.SetCallHomePortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
