"""parameter_write_history (Этап 2)

Revision ID: 00e6e74af911
Revises: 16cf39318ca9
Create Date: 2026-08-18 23:29:35.289607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00e6e74af911'
down_revision: Union[str, Sequence[str], None] = '16cf39318ca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameter_write_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=64), nullable=False),
    sa.Column('obis_code', sa.String(length=32), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', sa.Enum('SUCCESS', 'FAILURE', name='parameter_write_result'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parameter_write_history_created_at'), 'parameter_write_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_parameter_write_history_meter_id'), 'parameter_write_history', ['meter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parameter_write_history_meter_id'), table_name='parameter_write_history')
    op.drop_index(op.f('ix_parameter_write_history_created_at'), table_name='parameter_write_history')
    op.drop_table('parameter_write_history')
    # ### end Alembic commands ###
