"""call-home meters: is_call_home, nullable ip_address/port

Revision ID: 16cf39318ca9
Revises: 9a29937be7e1
Create Date: 2026-08-18 17:19:39.870223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16cf39318ca9'
down_revision: Union[str, Sequence[str], None] = '9a29937be7e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default нужен для существующих строк (иначе NOT NULL без
    # значения падает на непустой таблице); server_default сразу же
    # снимается — Python-модель уже сама подставляет default=False для
    # новых строк, БД-уровневый default не нужен постоянно.
    op.add_column('meters', sa.Column('is_call_home', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('meters', 'is_call_home', server_default=None)
    op.alter_column('meters', 'ip_address',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('meters', 'port',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meters', 'port',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('meters', 'ip_address',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('meters', 'is_call_home')
    # ### end Alembic commands ###
