"""load_profile_data (Этап 3)

Revision ID: 20f9659329f9
Revises: 00e6e74af911
Create Date: 2026-08-19 11:27:20.622032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20f9659329f9'
down_revision: Union[str, Sequence[str], None] = '00e6e74af911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('load_profile_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('obis_code', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('values_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meter_id', 'obis_code', 'timestamp', name='uq_load_profile_row')
    )
    op.create_index(op.f('ix_load_profile_data_meter_id'), 'load_profile_data', ['meter_id'], unique=False)
    op.create_index(op.f('ix_load_profile_data_timestamp'), 'load_profile_data', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_load_profile_data_timestamp'), table_name='load_profile_data')
    op.drop_index(op.f('ix_load_profile_data_meter_id'), table_name='load_profile_data')
    op.drop_table('load_profile_data')
    # ### end Alembic commands ###
