"""billing api keys, disconnect batches (Этап 5)

Revision ID: 2dd973aee6c7
Revises: 657b5eb22c1a
Create Date: 2026-08-19 12:42:02.137460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd973aee6c7'
down_revision: Union[str, Sequence[str], None] = '657b5eb22c1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='billing_api_key_status'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('disconnect_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.Enum('DISCONNECT', 'RECONNECT', name='disconnect_batch_operation'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'IN_PROGRESS', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED', name='disconnect_batch_status'), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['billing_api_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_id', 'idempotency_key', name='uq_disconnect_batch_idempotency')
    )
    op.create_index(op.f('ix_disconnect_batches_api_key_id'), 'disconnect_batches', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_disconnect_batches_batch_id'), 'disconnect_batches', ['batch_id'], unique=True)
    op.create_table('disconnect_batch_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('meter_serial', sa.String(length=32), nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'DONE', 'FAILED', name='disconnect_batch_item_status'), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['disconnect_batches.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disconnect_batch_items_batch_id'), 'disconnect_batch_items', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disconnect_batch_items_batch_id'), table_name='disconnect_batch_items')
    op.drop_table('disconnect_batch_items')
    op.drop_index(op.f('ix_disconnect_batches_batch_id'), table_name='disconnect_batches')
    op.drop_index(op.f('ix_disconnect_batches_api_key_id'), table_name='disconnect_batches')
    op.drop_table('disconnect_batches')
    op.drop_table('billing_api_keys')
    # ### end Alembic commands ###
