"""parameter_schemes, scheduled_jobs, notifications (Этап 4)

Revision ID: 657b5eb22c1a
Revises: 20f9659329f9
Create Date: 2026-08-19 11:55:42.411712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '657b5eb22c1a'
down_revision: Union[str, Sequence[str], None] = '20f9659329f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameter_schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cron_expression', sa.String(length=64), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('operation_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meter_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCEEDED', 'PARTIAL_FAILURE', 'FAILED', name='scheduled_job_run_status'), nullable=False),
    sa.Column('meters_total', sa.Integer(), nullable=False),
    sa.Column('meters_succeeded', sa.Integer(), nullable=False),
    sa.Column('meters_failed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scheduled_job_id'], ['scheduled_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_job_runs_scheduled_job_id'), 'scheduled_job_runs', ['scheduled_job_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('METER_OFFLINE', 'TAMPER_EVENT', 'SCHEDULED_JOB_FAILED', name='notification_category'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_job_id', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ),
    sa.ForeignKeyConstraint(['scheduled_job_id'], ['scheduled_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_category'), 'notifications', ['category'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.add_column('jobs', sa.Column('scheduled_job_run_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_jobs_scheduled_job_run_id'), 'jobs', ['scheduled_job_run_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'scheduled_job_runs', ['scheduled_job_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_scheduled_job_run_id'), table_name='jobs')
    op.drop_column('jobs', 'scheduled_job_run_id')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_category'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_scheduled_job_runs_scheduled_job_id'), table_name='scheduled_job_runs')
    op.drop_table('scheduled_job_runs')
    op.drop_table('scheduled_jobs')
    op.drop_table('parameter_schemes')
    # ### end Alembic commands ###
