"""meter status (installed/active), gateway call_home_port (Этап 6)

Revision ID: f8712d78dd15
Revises: 2dd973aee6c7
Create Date: 2026-08-19 14:00:00.415481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8712d78dd15'
down_revision: Union[str, Sequence[str], None] = '2dd973aee6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gateways', sa.Column('call_home_port', sa.Integer(), nullable=True))
    # В отличие от Enum-колонок, созданных вместе с CREATE TABLE (там
    # SQLAlchemy сам создаёт тип), ALTER TABLE ADD COLUMN требует, чтобы
    # тип meter_status уже существовал в БД — создаём его явно первым
    # шагом (checkfirst=True — безопасно перезапускать миграцию).
    meter_status_enum = postgresql.ENUM('INSTALLED', 'ACTIVE', name='meter_status')
    meter_status_enum.create(op.get_bind(), checkfirst=True)
    # server_default нужен, чтобы ALTER TABLE не упал на уже существующих
    # строках (счётчики, заведённые до Этапа 6, все считаются ACTIVE —
    # они полностью настроены, ручного заведения без пароля до этого
    # этапа не существовало). Убираем default сразу после заполнения,
    # чтобы дальше он не расходился со значением по умолчанию на
    # Python-стороне (models.Meter.status).
    op.add_column(
        'meters',
        sa.Column('status', meter_status_enum, nullable=False, server_default='ACTIVE'),
    )
    op.alter_column('meters', 'status', server_default=None)
    op.alter_column('meters', 'protocol_profile',
               existing_type=postgresql.ENUM('MODE_C', 'MODE_E', 'HDLC_DLMS', name='protocol_profile'),
               nullable=True)
    op.alter_column('meters', 'password_encrypted',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meters', 'password_encrypted',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.alter_column('meters', 'protocol_profile',
               existing_type=postgresql.ENUM('MODE_C', 'MODE_E', 'HDLC_DLMS', name='protocol_profile'),
               nullable=False)
    op.drop_column('meters', 'status')
    postgresql.ENUM(name='meter_status').drop(op.get_bind(), checkfirst=True)
    op.drop_column('gateways', 'call_home_port')
    # ### end Alembic commands ###
